name: Bug Report
title: "[Bug]: "
labels: bug
description: Report broken or incorrect behaviour
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a bug.
        Please note that this form is for bugs only!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
  - type: textarea
    attributes:
      label: System Information
      description: please fill your system informations
      value: >
        Operating System : [e.g. Windows 11]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: >
         If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.