blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Ask questions and discuss with other users of sourcefuck.
    url: https://github.com/hammamikhairi/sourcefuck/discussions